### ISSUE TITLE
Make the UI responsive

### ISSUE THREAD

**Issue by dolftax** [dolftax/sTeam-web-interface#13]
The top bar has a lot of columns and options. Figure out a way to make the column responsive (mobile-friendly).

**Comment by AkhilHector** [comment]
@dolftax is this the the screen you are talking about ? or did i miss something ?
![2](https://cloud.githubusercontent.com/assets/5903056/10366594/1389309a-6de9-11e5-9e70-86128c311bb6.png)

**Comment by dolftax** [comment]
Ah! So, right now, register is not implemented. Sign-up here - https://dev-back1.techgrind.asia/ and ping eMbee at #steam-devel to activate your account. With the same credentials, log in and you will understand the issue description.

**Comment by AkhilHector** [comment]
@dolftax ohk understood :dart:
