### ISSUE TITLE
Create routes to handle views

### ISSUE THREAD

**Issue by dolftax** [dolftax/sTeam-web-interface#7]
##### State 1 - If not logged in, whichever URL, 

- `/login` - workarea ( login view)

##### State 2 - If logged in

- `/home` || `/` - workarea ( list view ) [shared workarea]
- `/:username` - workarea ( list view ) [private workarea]
- `/:username/:room-name` - workarea ( list view )
- `/:username/:document-name` - workarea ( detailed view )
- `/:username/:container-name` - workarea ( error view )
- `/:username/:room-name/:sub-room-name` - workarea ( list view )
- `/:username/:room-name/:document-name` - workarea ( detailed view )
- `/xyz` - workarea ( error view )

PS: Handle the options in the breadcrumb accordingly.

**Comment by eMBee** [comment]
Excerpts from Jaipradeesh's message of 2015-06-10 15:39:31 +0200:
> - `/:username` - workarea ( list view )
> - `/:room-name` - workarea ( list view )
> - `/:document-name` - workarea ( detailed view )
> - `/:container-name` - workarea ( error view )
> - `/:room-name/:sub-room-name` - workarea ( list view )
> - `/:room-name/:document-name` - workarea ( detailed view )

how will you tell the difference between those routes?
i suspect that you need to make this into one route, send the whole path to
the server to find out what this is, and then choose a view accordingly

greetings, martin.

**Comment by dolftax** [comment]
I've edited the URLs. It makes sense now.

**Comment by dolftax** [comment]
The paths will not be handled by the client. Instead, be it room (or) document, the path is retrieved from the sTeam server itself and the same will be used.
